---
title: "Linear_models"
author: "Xin  He"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

## start

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

## fit a first model

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)
```

```{r}
fit

summary(fit)
coef(fit)
summary(fit)$coef
```

tidy the results

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "boro", "Boro:")) %>% 
  knitr::kable(digit = 3)

fit %>% 
  broom::glance()
```

## take a look at factors

```{r}
nyc_airbnb = 
nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),
    room_type = fct_infreq(room_type)
  )
```

refit

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)

fit %>%
  broom::tidy()
```


## diagnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = boro, y  = resid)) + 
  geom_violin() + 
  ylim(-500,  500)
```

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y  = resid)) + 
  geom_point() + 
  ylim(-500,  500)

modelr::add_predictions(nyc_airbnb, fit)
```

## nesting

```{r}
fit_interaction = lm(price ~ stars  * boro + room_type * boro, data = nyc_airbnb) %>% 
  broom::tidy()
```

```{r}
nyc_airbnb %>% 
  filter(boro ==  "Brooklyn") %>% 
  lm(price ~ stars + room_type, data = .) %>%
  broom::tidy()
```

map

```{r}
nyc_airbnb %>% 
  nest(data  = -boro) %>% 
  mutate(
    models  = map(.x = data, ~lm(price ~ stars + room_type, data = .)),
    results  =  map(models, broom::tidy)
  ) %>% 
  select(-data) %>% 
  unnest(results)
```

nest neighborhhods

```{r}
nyc_airbnb %>% 
  filter(boro == "Manhattan") %>% 
  nest(data  = -neighborhood) %>% 
  mutate(
    models  = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    results  =  map(models, broom::tidy)
  ) %>% 
  select(neighborhood, results) %>% 
  unnest(results)
```

```{r}
manhattan_nest_lm_res  = 
nyc_airbnb %>% 
  filter(boro == "Manhattan") %>% 
  nest(data  = -neighborhood) %>% 
  mutate(
    models  = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    results  =  map(models, broom::tidy)
  ) %>% 
  select(neighborhood, results) %>% 
  unnest(results)
```

```{r}
manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

```{r}
nyc_airbnb %>% 
  filter(neighborhood == "NoHo", room_type  == "Shared room")
```













